### ISSUE TITLE
Update the installation instructions on https://packagecontrol.io/installation

### ISSUE THREAD

**Issue by evandrocoan** [wbond/packagecontrol.io#112] opened 2019-04-17 00:10 UTC
Now you can install Package Control directly within Sublime Text.

Therefore, the page https://packagecontrol.io/installation could reflect this.

**Comment by OdatNurd** [comment] 2019-10-04 04:56
This looks like a duplicate of #97.

**Closed** 2019-10-04 21:39 UTC
